image: atlassian/default-image:4

pipelines:
  branches:
    staging:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          # Note: you will need something like this to run on a remote server in environment if you need private network access
          # runs-on:
          #   - self.hosted
          #   - linux.shell
          #   - v3
          script:
            - ENVIRONMENT=staging ./migrate.sh
          services:
            - docker
    production:
      - step:
          name: 'Deployment to Production'
          deployment: production
          # Note: you will need something like this to run on a remote server in environment if you need private network access
          # runs-on:
          #   - self.hosted
          #   - linux.shell
          #   - v3
          script:
            - ENVIRONMENT=prod ./migrate.sh
          services:
            - docker
  custom:
    repair-staging:
      - step:
          # Note: you will need something like this to run on a remote server in environment if you need private network access
          # runs-on:
          #   - self.hosted
          #   - linux.shell
          #   - v3
          script:
            - ENVIRONMENT=staging ./repair.sh
          services:
            - docker
    repair-production:
      - step:
          # Note: you will need something like this to run on a remote server in environment if you need private network access
          # runs-on:
          #   - self.hosted
          #   - linux.shell
          #   - v3
          script:
            - ENVIRONMENT=prod ./repair.sh
          services:
            - docker
