name: Terraform Deployment

on:
  push:
    branches:
      - production
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        env:
          PASS_STAGING: ${{ secrets.PASS_STAGING }}
        run: |
          chmod +x ./*.sh
          ENVIRONMENT=staging ./migrate.sh

      - name: Deploy to Production
        if: github.ref == 'refs/heads/production'
        env:
          PASS_PROD: ${{ secrets.PASS_PROD }}
        run: |
          chmod +x ./*.sh
          ENVIRONMENT=prod ./migrate.sh
